variables:
  PUBLIC_URL: https://use-vechain.examples.vechain.energy

stages:
  - build
  - deploy

build storybook:
  stage: build
  image: node:16
  script:
    - yarn install
    - cd example
    - yarn install
    - yarn run build-storybook
  artifacts:
    paths:
      - example/storybook-static
    expire_in: 1 day


pages:
  stage: deploy
  image: node:16
  script:
    - mv example/storybook-static public
  environment:
    name: "Gitlab Pages"
    url: $PUBLIC_URL
  artifacts:
    paths:
    - public
